param resourceName string = 'acctest0001'
param location string = 'westeurope'

resource grafana 'Microsoft.Dashboard/grafana@2022-08-01' = {
  name: resourceName
  location: location
  properties: {
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Disabled'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
  sku: {
    name: 'Standard'
  }
}
